# Site settings
title: Programming and programming
email: programming@programming
description: > # this means to ignore newlines until "baseurl:"
  Programming and programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kenpeter.github.io" # the base hostname & protocol for your site
twitter_username: kenpeter 
github_username:  kenpeter

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml' 


# Build settings
markdown: kramdown
